# Generated by Django 5.1.2 on 2024-10-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0002_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
