# Generated by Django 5.1.2 on 2024-10-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0005_osoba_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='data_dodania',
        ),
    ]
