# Generated by Django 5.1.2 on 2024-10-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paw_app', '0008_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
